name: food_store_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5

  # state
  get_it: ^7.2.0
  provider: ^6.0.5

  # utils
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.17.0

  # remote
  retrofit: ^3.0.1
  dio: ^4.0.4

  #monitoring
  sentry_flutter: ^7.7.0
  awesome_dio_interceptor: ^0.0.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.1.3
  retrofit_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
